CREATE DATABASE AgileDatabase
GO
USE AgileDatabase
GO
-- Tạo bảng CATEGORY
CREATE TABLE CATEGORIES (
    CategoryId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    CategoryName NVARCHAR(255) NOT NULL,
    CategoryNameVN NVARCHAR(255) NOT NULL
);

-- Tạo bảng SUPPLIER
CREATE TABLE SUPPLIERS (
    SupplierId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    SupplierName NVARCHAR(255) NOT NULL,
    Logo NVARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL,
    Phone NVARCHAR(10) NOT NULL
);

-- Tạo bảng USER
CREATE TABLE USERS (
    UserId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Username NVARCHAR(255) NOT NULL,
    Password NVARCHAR(50) NOT NULL,
    FullName NVARCHAR(50) NOT NULL,
    Email NVARCHAR(255) NOT NULL,
    Phone NVARCHAR(50) NOT NULL,
    Role NVARCHAR(50) NOT NULL
);

-- Tạo bảng ORDER
CREATE TABLE ORDERS (
    OrderId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    OrderDate DATETIME NOT NULL,
    ReceiveDate DATETIME NOT NULL,
    Address NVARCHAR(255) NOT NULL,
    FullName NVARCHAR(255) NOT NULL,
    PaymentMethod NVARCHAR(50) NOT NULL,
    Transportation NVARCHAR(50) NOT NULL,
    TransportFee FLOAT NOT NULL,
    StatusCode NVARCHAR(50) NOT NULL,
    UserId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES USERS(UserId)
);

-- Tạo bảng PRODUCT
CREATE TABLE PRODUCTS (
    ProductId INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    ProductName NVARCHAR(255) NOT NULL,
    UnitPrice FLOAT NOT NULL,
    Image NVARCHAR(255) NOT NULL,
    Description NVARCHAR(255) NOT NULL,
    CategoryId INT NOT NULL,
    SupplierId INT NOT NULL,
    FOREIGN KEY (CategoryId) REFERENCES CATEGORIES(CategoryId),
    FOREIGN KEY (SupplierId) REFERENCES SUPPLIERS(SupplierId)
);

-- Tạo bảng ORDER_DETAILS
CREATE TABLE ORDER_DETAILS (
    OrderDetailsId INT IDENTITY(1,1) PRIMARY KEY,
    OrderId INT,
    ProductId INT,
    UnitPrice FLOAT NOT NULL,
    Amount INT NOT NULL,
    Discount DECIMAL(18, 2) NOT NULL,
    FOREIGN KEY (OrderId) REFERENCES [ORDERS](OrderId),
    FOREIGN KEY (ProductId) REFERENCES PRODUCTS(ProductId)
);
