CREATE DATABASE ACCOUNT;
GO

USE ACCOUNT;
GO

-- Table for Users
CREATE TABLE Users (
    Id NVARCHAR(450) NOT NULL PRIMARY KEY,
    UserName NVARCHAR(256) NOT NULL,
	FullName NVARCHAR(256) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    PasswordHash NVARCHAR(MAX) NOT NULL,
    PhoneNumber NVARCHAR(MAX) NOT NULL
);
GO

-- Table for Roles
CREATE TABLE Roles (
    Id NVARCHAR(450) NOT NULL PRIMARY KEY,
    NameRole NVARCHAR(256) NOT NULL,
    NormalizedName NVARCHAR(256) NOT NULL
);
GO

-- Table for UserRoles 
CREATE TABLE UserRoles (
    UserId NVARCHAR(450) NOT NULL,
    RoleId NVARCHAR(450) NOT NULL,
    PRIMARY KEY (UserId, RoleId),
    FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    FOREIGN KEY (RoleId) REFERENCES Roles(Id) ON DELETE CASCADE
);
GO

DELETE Users;
DELETE Roles;
DELETE UserRoles;

DROP DATABASE ACCOUNT